# HT跑测音频集
- group_name: 你好小迪主驾
  audio_list:
    - path: in_06-03_17-14-51-309.pcm
      doa: 1
      wakeup_count: 180
    - path: in_06-17_16-26-54-953.pcm
      doa: 1
      wakeup_count: 180
- group_name: 你好小迪副驾
  audio_list:
    - path: in_06-04_11-58-34-250.pcm
      doa: 2
      wakeup_count: 180
    - path: in_06-04_15-10-10-789.pcm
      doa: 2
      wakeup_count: 180
    - path: in_06-04_11-02-40-460.pcm
      doa: 2
      wakeup_count: 180
    - path: in_06-17_14-53-00-115.pcm
      doa: 2
      wakeup_count: 180
- group_name: 你好小迪主驾后排
  audio_list:
    - path: in_06-04_14-12-12-543.pcm
      doa: 3
      wakeup_count: 180
    - path: in_06-04_15-28-08-649.pcm
      doa: 3
      wakeup_count: 180
    - path: in_06-04_13-40-07-748.pcm
      doa: 3
      wakeup_count: 180
    - path: in_06-17_14-30-13-588.pcm
      doa: 3
      wakeup_count: 180
- group_name: 你好小迪副驾后排
  audio_list:
    - path: in_06-04_12-12-01-720.pcm
      doa: 4
      wakeup_count: 180
    - path: in_06-04_14-57-50-676.pcm
      doa: 4
      wakeup_count: 180
    - path: in_06-04_11-22-43-918.pcm
      doa: 4
      wakeup_count: 180
    - path: in_06-17_16-41-04-958.pcm
      doa: 4
      wakeup_count: 180
# - group_name: 误唤醒
  # audio_list:
    # - path: in_08-17_19-34-26-126.pcm
      # wakeup_count: 0
      # type: 1
    # - path: in_09-06_11-34-47-898.pcm
      # wakeup_count: 1
      # type: 1
